name: "HCL AppScan SAST"

permissions:
  statuses: write
  contents: read

on:
  workflow_dispatch:
jobs:
  scan:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get current date
        id: date
        run: echo "date=$(Get-Date -Format 'yyyy-MM-dd HH:mm')" >> $env:GITHUB_OUTPUT
        
      - name: Run AppScan SAST scan
        id: appscan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@Issue_Fix_Main_Wait_For_Analysis_False
        with:
          asoc_key: ${{ secrets.ASOC_KEY }}
          asoc_secret: ${{ secrets.ASOC_SECRET }}
          application_id: ${{ secrets.ASOC_APP_ID }}
          scan_name: "SAST ${{ steps.date.outputs.date }} Incremental scan"
          service_url:  https://lp2-ap-52011081.appscan-test.local
          static_analysis_only: true
          acceptssl: true
          personal_scan: false
          wait_for_analysis: false
          incremental_scan: false
          fail_for_noncompliance: false
          failure_threshold: High
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
