
name: "HCL AppScan SAST for AppScan 360 Instance"
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@main
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: ${{ secrets.ASOC_APP_ID }}
          service_url: https://cloud.appscan.com
          acceptssl: true
          scan_name: "SAST ${{ steps.date.outputs.date }} Incremental scan"
          personal_scan: false
          wait_for_analysis: true
          incremental_scan: true
          fail_for_noncompliance: true
          failure_threshold: High
env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
